/**
 * generation/src/utils/xml-parser.ts
 *
 * Parses the XML envelope returned by the LLM chunking calls.
 *
 * LLM output format:
 *   <chunks>
 *     <chunk>
 *       <front_matter>YAML block (no chunk_id, no source)</front_matter>
 *       <content>markdown body</content>
 *     </chunk>
 *   </chunks>
 *
 * Pipeline responsibilities (NOT the LLM's job):
 *   - chunk_id → always UUID v4, generated here via crypto.randomUUID()
 *   - source   → PDF filename only, injected by the caller
 *
 * Chunks with status: skipped are silently dropped.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

/** Raw parsed output before pipeline metadata is injected. */
export interface RawParsedChunk {
  topic: string;
  summary: string;
  triggers: string[];
  has_conditions: boolean;
  /** Always [] — related_chunks are computed in the compile stage. */
  related_chunks: [];
  status: string;
  /** Full markdown body (Context + Response + Escalation). */
  content: string;
}

/** Final chunk ready to be written to disk as a .md file. */
export interface ParsedChunk {
  /** UUID v4 — generated by the pipeline, never by the LLM. */
  chunk_id: string;
  /** PDF filename only, e.g. "My Document.pdf". Not a full path. */
  source: string;
  topic: string;
  summary: string;
  triggers: string[];
  has_conditions: boolean;
  related_chunks: [];
  status: "active" | "review" | "deprecated";
  content: string;
}

// ─── XML parser ───────────────────────────────────────────────────────────────

/**
 * Extract all <chunk>...</chunk> blocks from an LLM XML response.
 * Drops any chunk where status == "skipped".
 * Does NOT inject chunk_id or source — call injectChunkMetadata() for that.
 */
export function parseXmlResponse(xml: string): RawParsedChunk[] {
  // Find all <chunk> blocks (non-greedy, handles multiline content)
  const chunkBlocks = [...xml.matchAll(/<chunk>([\s\S]*?)<\/chunk>/g)].map(
    (m) => m[1]!,
  );

  const results: RawParsedChunk[] = [];

  for (const block of chunkBlocks) {
    // Extract <front_matter> and <content> sections
    const fmMatch = block.match(/<front_matter>([\s\S]*?)<\/front_matter>/);
    const contentMatch = block.match(/<content>([\s\S]*?)<\/content>/);

    if (!fmMatch) continue; // Malformed block — skip silently

    const fm = fmMatch[1]!.trim();
    const content = contentMatch ? contentMatch[1]!.trim() : "";

    // ── Parse status first — drop skipped chunks immediately ──────────────
    const status = fm.match(/^status:\s*(\S+)$/m)?.[1]?.trim() ?? "active";
    if (status === "skipped") continue;

    // ── Parse scalar fields ───────────────────────────────────────────────
    // Handle both quoted and unquoted YAML values
    const topic =
      fm.match(/^topic:\s*"([^"]+)"/m)?.[1]?.trim() ??
      fm.match(/^topic:\s*(.+)$/m)?.[1]?.trim() ??
      "";

    const summary =
      fm.match(/^summary:\s*"([^"]+)"/m)?.[1]?.trim() ??
      fm.match(/^summary:\s*(.+)$/m)?.[1]?.trim() ??
      "";

    const has_conditions =
      fm.match(/^has_conditions:\s*(true|false)$/m)?.[1] === "true";

    // ── Parse triggers list ───────────────────────────────────────────────
    const triggersSection = fm.match(
      /^triggers:\s*\n((?:[ \t]+-[ \t]+.+\n?)*)/m,
    );
    const triggers = triggersSection?.[1]
      ? [
          ...triggersSection[1].matchAll(/^[ \t]+-[ \t]+"?([^"\n]+?)"?\s*$/gm),
        ].map((m) => m[1]!.trim())
      : [];

    results.push({
      topic,
      summary,
      triggers,
      has_conditions,
      related_chunks: [],
      status,
      content,
    });
  }

  return results;
}

// ─── Metadata injection ───────────────────────────────────────────────────────

/**
 * Inject pipeline-managed fields (chunk_id, source) into a raw parsed chunk.
 * This is the boundary between LLM output and pipeline ownership.
 *
 * @param raw    Output from parseXmlResponse()
 * @param source PDF filename only (not a full path), e.g. "My Document.pdf"
 */
export function injectChunkMetadata(
  raw: RawParsedChunk,
  source: string,
): ParsedChunk {
  return {
    chunk_id: crypto.randomUUID(), // UUID v4 — Bun/Node built-in
    source,
    topic: raw.topic,
    summary: raw.summary,
    triggers: raw.triggers,
    has_conditions: raw.has_conditions,
    related_chunks: [],
    status: raw.status as "active" | "review" | "deprecated",
    content: raw.content,
  };
}

// ─── Markdown assembler ───────────────────────────────────────────────────────

/**
 * Assemble a ParsedChunk into the final .md file content.
 *
 * Output structure:
 *   ---
 *   chunk_id: <uuid>
 *   source: <filename>
 *   topic: "..."
 *   summary: >
 *     <one sentence>
 *   triggers:
 *     - "..."
 *   has_conditions: true/false
 *   related_chunks: []
 *   status: active
 *   ---
 *
 *   ## Context
 *   ...
 *   ## Response
 *   ...
 *   ## Escalation
 *   ...
 */
export function assembleChunkMarkdown(chunk: ParsedChunk): string {
  const lines: string[] = [];

  // ── YAML front matter ─────────────────────────────────────────────────────
  lines.push("---");
  lines.push(`chunk_id: ${chunk.chunk_id}`);
  lines.push(`source: ${chunk.source}`);
  lines.push(`topic: "${chunk.topic.replace(/"/g, "'")}"`);
  lines.push(`summary: >`);
  lines.push(`  ${chunk.summary}`);
  lines.push(`triggers:`);
  for (const t of chunk.triggers) {
    lines.push(`  - "${t.replace(/"/g, "'")}"`);
  }
  lines.push(`has_conditions: ${chunk.has_conditions}`);
  lines.push(`related_chunks: []`);
  lines.push(`status: ${chunk.status}`);
  lines.push("---");
  lines.push("");

  // ── Markdown body (from LLM, verbatim) ───────────────────────────────────
  lines.push(chunk.content);
  lines.push(""); // trailing newline

  return lines.join("\n");
}
